config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#welcome'
  resources :songs
  resources :albums
end

app/models/album.rb
class Album < ApplicationRecord
  validates :name, presence: true
  validates :year, presence: true, numericality: { only_integer: true }
  has_many :songs, dependent: :destroy

  def time_since_was_released
    today = Date.today.year
    today - year
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord
  validates :name, presence: true
  belongs_to :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(params.require(:album).permit(:name, :year))
    if @album.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def show
    @album = Album.find(params[:id])
    @songs = Song.where(album: @album)
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(params.require(:album).permit(:name, :year))
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    album = Album.find(params[:id])
    album.destroy
    redirect_to root_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def welcome
    @songs = Song.all.order(:created_at)
    @albums = Album.all.order(:name)
	end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def new
    @song = Song.new
    @albums = Album.all
  end

  def create
    @song = Song.new(params.require(:song).permit(:name, :album_id))
    if @song.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @song = Song.find(params[:id])
    @albums = Album.all
  end

  def update
    @song = Song.find(params[:id])
    if @song.update(params.require(:song).permit(:name, :album_id))
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    song = Song.find(params[:id]) #nao precisa do @ pq nao tem a view
		song.destroy
		redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/edit.html.erb
<ul>
  <% @album.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

<h2>Edit your album:</h2>

<%= form_for @album do |f| %>
	<p><%= f.label :name, 'Name' %>
	<%= f.text_field :name %></p>
  <p><%= f.label :year, 'Year' %>
  <%= f.text_field :year %></p>
  <button type="submit" class="btn btn-outline-primary">Edit</button>
<% end %>

app/views/albums/new.html.erb
<ul>
  <% @album.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

<h2 class>New album:</h2>
<%= form_for @album do |f| %>
	<p><%= f.label :name, 'Name' %>
	<%= f.text_field :name %></p>
  <p><%= f.label :year, 'Year' %>
  <%= f.text_field :year %></p>
  <button type="submit" class="btn btn-outline-primary">Create</button>
<% end %>

app/views/albums/show.html.erb
<div class="container">
  <section class="album-header">
    <%= image_tag 'cd.jpg', class: "img-thumbnail" %>
    <div class="text-left container-x">
      <h1 class="font-weight-light"><%= @album.name %></h1>
      <h3 class="font-weight-light"><%= @album.year %></h3>
    </div>
  </section>
  <% @songs.each do |s|%>
    <p class="font-weight-light"><%= s.name%></p>
  <% end %>
</div>

app/views/home/welcome.html.erb
<div class="text-center">
	<%= image_tag 'example.png', class: "img-fluid" %>
	<h1>Welcome to your Songs List!!</h1>
</div>

<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="songs-tab" data-toggle="tab" href="#song" role="tab" aria-controls="song">Songs</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="albums-tab" data-toggle="tab" href="#album" role="tab" aria-controls="album">Albums</a>
  </li>
</ul>

<!-- Tab panes -->
<div class="tab-content tab-content-margin">
  <div class="tab-pane active" id="song" role="tabpanel" aria-labelledby="songs-tab">
		<h2>Your songs</h2>
		<ul class="list-group list-group-flush">
			<% @songs.each do |song| %>
				<li class="list-group-item d-flex justify-content-between align-items-center">
					<p class="p-no-margin"><%= song.name %> <small>From: <%= song.album.name %></small></p>
					<div>
						<a class="btn btn-outline-primary" href="<%= edit_song_path(song) %>" role="button">Edit</a>
						<a class="btn btn-outline-dark" data-confirm="Delete this song?" data-method="delete"
						href="<%= song_path(song) %>" >Delete</a>
					</div>
				</li>
			<% end %>
		</ul>
		<a class="btn btn-outline-primary button-margin" href="<%= new_song_path role="button" %>">New song</a>
	</div>
  <div class="tab-pane" id="album" role="tabpanel" aria-labelledby="abums-tab">
		<h2>Your albums</h2>
		<div class="card-columns">
				<% @albums.each do |album| %>
					<div class="card">
						<div class="card-body">
							<h5 class="card-title font-weight-light text-right"><%= album.name %></h5>
							<h6 class="text-right small font-weight-light"><%= album.year %></h6>
							<div class="text-center image-container">
								<%= image_tag 'cd.jpg', class: "img-fluid"%>
							</div>
							<%= link_to 'Edit', edit_album_path(album) %>
							<%= link_to 'Show', album_path(album) %>
						  <%= link_to 'Delete', album_path(album), method: :delete,
						  data: { confirm: 'Delete this album? All releated song will also be deleted.'}%>
						</div>
					</div>
				<% end %>
		</div>
		<a class="btn btn-outline-primary button-margin" href="<%= new_album_path role="button" %>">New album</a>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Songs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/songs/edit.html.erb
<ul>
  <% @song.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

<h2>Edit your song:</h2>
<%= form_for @song do |f| %>
	<p><%= f.label :name, 'Name' %>
	<%= f.text_field :name %></p>
  <p><%= f.label :album_id, 'Album' %>
  <%= f.collection_select(:album_id, @albums, :id, :name) %></p>
	<button type="submit" class="btn btn-outline-primary">Edit</button>
<% end %>

app/views/songs/new.html.erb
<ul>
  <% @song.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

<h2>New song</h2>
<%= form_for @song do |f| %>
	<p><%= f.label :name, 'Name: ' %>
	<%= f.text_field :name %></p>
  <p><%= f.label :album_id, 'Album' %>
	<%= f.collection_select(:album_id, @albums, :id, :name) %></p>
  <button type="submit" class="btn btn-outline-primary">Create</button>
<% end %>